### ISSUE TITLE
Integration of Aztec into wpandroid

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-Android#52]
Integrate the Aztec editor into wpandroid to test how it works with real WP posts.

- [x] Image download ([issue](https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/201)/[pull request](https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/202))
- [x] Image display ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/5045)/[pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/5059))
- [x] Image upload ([issue](https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/218)/[pull request](https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/226))
- [x] Media menu ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/5046)/[pull request](https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/226))
- [x] All issues marked with [milestone 1.0](https://github.com/wordpress-mobile/WordPress-Aztec-Android/milestone/3)
